import { afterEach, beforeEach, describe, expect, test } from 'vitest'

import { UserSignupForm } from '@/app/_types/validation-schema'
import { makeUserData, scene, testClient } from '@/testing/scene'
import { tryCatch } from '@/utils/try-catch'

import { handleSupabaseSignInWithPassword, handleSupabaseSignOut, handleSupabaseSignUpWithPassword } from './auth-handlers'

// Define different test users only for auth testing so we can create a delete as needed without affecting other tests
const AUTH_TEST_USER_1 = {
  email: 'auth.test.user@example.com',
  password: 'testpassword123',
  displayName: 'Test User',
  handle: 'authuser',
}

const AUTH_TEST_USER_2 = {
  email: 'auth.test.user2@example.com',
  password: 'testpassword123',
  displayName: 'Test User 2',
  handle: 'authuser2',
}

function makeAuthTestUserData(base: typeof AUTH_TEST_USER_1 = AUTH_TEST_USER_1, overrides: Partial<typeof AUTH_TEST_USER_1> = {}) {
  return makeUserData(scene.scope(), { ...base, ...overrides })
}

describe('authHandlers', () => {
  // Track created test user IDs to clean up after tests
  const createdTestUserIds = new Set<string>()
  const addTestUserToCleanup = (id: string) => createdTestUserIds.add(id)
  const cleanUpTestUsers = async () => {
    await Promise.all(
      Array.from(createdTestUserIds).map(async (id) => {
        const { error } = await tryCatch(testClient.auth.admin.deleteUser(id))
        if (error) {
          console.error('Error cleaning up test user:', error)
          return Promise.resolve(null)
        }
        createdTestUserIds.delete(id)
      })
    )
  }

  beforeEach(async () => {
    scene.setup()
    await Promise.all([
      scene.withoutUser({ handle: AUTH_TEST_USER_1.handle, supabaseClient: testClient }),
      scene.withoutUser({ handle: AUTH_TEST_USER_2.handle, supabaseClient: testClient }),
      cleanUpTestUsers(),
    ])
  })

  afterEach(async () => {
    await Promise.all([
      scene.cleanup(),
      scene.withoutUser({ handle: AUTH_TEST_USER_1.handle, supabaseClient: testClient }),
      scene.withoutUser({ handle: AUTH_TEST_USER_2.handle, supabaseClient: testClient }),
      cleanUpTestUsers(),
    ])
  })

  describe('signUp', () => {
    test('should successfully create a new user account', async () => {
      const authUser = makeAuthTestUserData()
      // Act
      const testUser = await handleSupabaseSignUpWithPassword(testClient, authUser)

      addTestUserToCleanup(testUser.id)

      // Assert
      expect(testUser).toBeDefined()
      expect(testUser.id).toBeDefined()

      // Verify user exists in auth
      const { data: authUserData } = await testClient.auth.admin.getUserById(testUser.id)
      expect(authUserData.user).toBeDefined()
      expect(authUserData.user?.email).toBe(authUser.email)
    })

    test('should throw error when email is already taken', async () => {
      const authUser = makeAuthTestUserData()
      const existing = await handleSupabaseSignUpWithPassword(testClient, authUser)
      addTestUserToCleanup(existing.id)

      // Use same email as first user
      const userSignupData: UserSignupForm = {
        email: authUser.email,
        password: authUser.password,
      }

      // Act & Assert
      await expect(handleSupabaseSignUpWithPassword(testClient, userSignupData)).rejects.toThrow()
    })
  })

  describe('signIn', () => {
    test('should successfully sign in existing user', async () => {
      // Arrange
      const testUser = await scene.hasUser({ ...AUTH_TEST_USER_1, supabaseClient: testClient })

      // Act
      const result = await handleSupabaseSignInWithPassword(testClient, {
        email: testUser.email,
        password: AUTH_TEST_USER_1.password,
      })

      // Assert
      expect(result).toBeDefined()
      expect(result.authUserId).toBe(testUser.id)
    })

    test('should throw error when credentials are invalid', async () => {
      // Act & Assert
      await expect(
        handleSupabaseSignInWithPassword(testClient, {
          email: 'nonexistent@example.com',
          password: 'wrongpassword',
        })
      ).rejects.toThrow()
    })
  })

  describe('signOut', () => {
    test('should successfully sign out user', async () => {
      // Arrange
      // Create and sign in user
      const created = await scene.hasUser({ ...AUTH_TEST_USER_1, supabaseClient: testClient })
      await handleSupabaseSignInWithPassword(testClient, {
        email: created.email,
        password: AUTH_TEST_USER_1.password,
      })

      // Act & Assert
      await expect(handleSupabaseSignOut(testClient, '/')).resolves.not.toThrow()
    })
  })

  /* Skip testing email update flow
   * authOperations.updateEmail calls updateUser which requires client side session to be present.
   */

  /* Skip testing password reset flow
   * The password reset flow involves:
   * - Client side session to be present
   * - Email delivery of reset tokens
   * - Time-sensitive tokens generated by Supabase
   * - Complex session management during reset process
   */
})
